<?xml version="1.0"?>
<package format="2">
  <name>stepit_plugin_publisher_ros</name>
  <version>0.0.0</version>
  <description>ROS publisher plugin for StepIt.</description>
  <maintainer email="jewel@zju.edu.cn">jewel</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>diagnostic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>roscpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
</package>
