stepit_declare_plugin(NAME publisher_ros2 DEPENDS ros2_base)
set(missing_packages "")
foreach (package ament_cmake diagnostic_msgs geometry_msgs rclcpp sensor_msgs std_msgs)
  find_package(${package} QUIET)
  if (NOT ${package}_FOUND)
    list(APPEND missing_packages ${package})
  endif ()
endforeach ()
if (missing_packages)
  string(REPLACE ";" ", " missing_packages_text "${missing_packages}")
  stepit_plugin_mark_unbuildable("Missing CMake package(s): ${missing_packages_text}.")
  return()
endif ()
