set(STEPIT_PLUGIN_PATHS
    control/console
    example/debugging_helper
    field/base
    field/python
    integration/redis
    integration/ros
    integration/ros2
    joystick/base
    joystick/redis
    joystick/udp
    joystick/usb
    nnrt/base
    nnrt/onnxruntime
    nnrt/tensorrt
    nnrt/torchjit
    modular_policy/base
    modular_policy/nn
    modular_policy/locomotion
    modular_policy/motion_tracking
    modular_policy/redis
    modular_policy/ros
    modular_policy/ros2
    modular_policy/locomotion_ros
    modular_policy/locomotion_ros2
    publisher/csv
    robot/deeprobotics/lite3
    robot/deeprobotics/x30
    robot/unitree/aliengo
    robot/unitree/b1
    robot/unitree/go1
    robot/unitree2
    robot/unitree2_ros2
)
