stepit_declare_plugin(NAME modular_policy_locomotion_ros2 DEPENDS modular_policy_locomotion ros2_base)
set(missing_packages "")
foreach (package geometry_msgs grid_map_msgs grid_map_ros nav_msgs rclcpp sensor_msgs std_msgs tf2_ros)
  find_package(${package} QUIET)
  if (NOT ${package}_FOUND)
    list(APPEND missing_packages ${package})
  endif ()
endforeach ()
if (missing_packages)
  string(REPLACE ";" ", " missing_packages_text "${missing_packages}")
  stepit_plugin_mark_unbuildable("Missing CMake package(s): ${missing_packages_text}.")
  return()
endif ()
