stepit_declare_plugin(NAME joystick_ros2 DEPENDS joystick_base ros2_base)
set(missing_packages "")
find_package(ament_cmake QUIET)
if (NOT ament_cmake_FOUND)
  list(APPEND missing_packages ament_cmake)
endif ()
find_package(rclcpp QUIET)
if (NOT rclcpp_FOUND)
  list(APPEND missing_packages rclcpp)
endif ()
find_package(sensor_msgs QUIET)
if (NOT sensor_msgs_FOUND)
  list(APPEND missing_packages sensor_msgs)
endif ()
if (missing_packages)
  string(REPLACE ";" ", " missing_packages_text "${missing_packages}")
  stepit_plugin_mark_unbuildable("Missing CMake package(s): ${missing_packages_text}.")
  return()
endif ()
